### ISSUE TITLE
How to get it working (22/09/2022)

### ISSUE THREAD

**Issue by kliao1** [MURDriverless/depth_estimation#1]
# Context
The 2021 team didn't quite leave enough information on how to run this (oops).

# TODO
- [ ] run the rosbags and demonstrate how to push the images through the pipeline
- [x] show where the "pipeline" is modularised
- [ ] document the input and output of the pipeline

**Comment by kliao1** [comment]
We tried running `depth_estimation` out of the box after cloning it from the repo. There seems to be some problem with finding the xfeatures2d from opencv. I suspect opencv wasn't installed properly.

Instead, we found a `Pre-2022` directory in the SSD in the Jetson. In this directory, we followed:
`mur_stereo` -> `calibration` -> `learnopencv` -> `ObjectDetection-YOLO`

Here, we used the following commands:
```
mkdir build && cd build
cmake ..
make
cd ..
./build/object_detection_yolo --image=<your-image-name>.jpg
```

While this enables us to test the training models, it is far from a solution since the 2022 goal is to integrate everything.

**Comment by kliao1** [comment]
To run both images, use the following commands:
```
./build/object_detection_yolo --left_image=hello.jpg --right_image=hello.jpg
./build/object_detection_yolo --left_vid=hello.mp4 --right_vid=hello.mp4
```

https://github.com/MURDriverless/depth_estimation/blob/fe37e3e994e1bb194074fd04b37a74f875d63ce9/object_detection_yolo.cpp#L772
From this section of the code outlines the epipolar geometry section that is used for computing the x,y, and z coordinates

https://github.com/MURDriverless/depth_estimation/blob/fe37e3e994e1bb194074fd04b37a74f875d63ce9/object_detection_yolo.cpp#L115
From this section outlines the camera calibration and setup

https://github.com/MURDriverless/depth_estimation/blob/fe37e3e994e1bb194074fd04b37a74f875d63ce9/object_detection_yolo.cpp#L176
From this section outlines the config options for how to run the stereo pipeline

https://github.com/MURDriverless/depth_estimation/blob/fe37e3e994e1bb194074fd04b37a74f875d63ce9/object_detection_yolo.cpp#L335
This `net` refers to darknet

**Comment by kliao1** [comment]
Here's some of my notes on running darknet
[24.08_darknet_commands.odt](https://github.com/MURDriverless/depth_estimation/files/9621705/24.08_darknet_commands.odt)

It should be useful if you want to retrain your YOLO model and test how it fares for different datasets. Not useful at all for integration but hey, one step at a time
