### ISSUE TITLE
Run stereo pipeline in ROS

### ISSUE THREAD

**Issue by kliao1** [MURDriverless/depth_estimation#2]
# Context
- We want to run the rosbags through the pipeline and get the output published on a ros topic

# TODO
- [ ] how to read the ros topics that the rosbags will publish to, into the pipeline
       - this might be a good reference for setting up ROS instructions (https://github.com/MURDriverless/both_cam_acq/blob/87c47ecd349e17cee18c024594209bf7a6f41d7b/mur_stereo_acq_left/src/mur_stereo_basler/src/main.cpp#L124) 
 - [ ] push the images through the pipeline
 - [ ] make sure that the depth estimation is correct (I'd advise to write some simple test cases and push them to git :) )
 - [ ] write some code to publish the ros messages to the ros topic that SLAM is listening to (these would be the (x,y,z) coordinates and whatever else your SLAM guy needs)

# ROS Topic Format (Output from Stereo Pipeline)
- (x,y,z) coordinates
- time stamp
- colour of cone

You might want to create your own ros message format e.g., https://github.com/MURDriverless/mur_common/blob/master/msg/cone_msg.msg
